
[general]
# Windowsの場合
# WSL2を利用しているなら、WindowsのAlacrittyからWSL2のシェルを起動
import = [
    "./nord.toml",
    "./alacritty-windows.toml"
] # Linux/macOS ではこのパスは存在しないか、読み込まれない

[font]
bold = { family = "HackGen Console NF", style = "Bold" }
bold_italic = { family = "HackGen Console NF", style = "Bold Italic" }
italic = { family = "HackGen Console NF", style = "Italic" }
normal = { family = "HackGen Console NF", style = "Regular" }
size = 14.0

[window]
option_as_alt = "Both"
# startup_mode = "Fullscreen"

