[mgr]
ratio = [4, 4, 0]
show_hidden = true

[opener]
edit = [
	{ run = '$HOME/dotfiles/scripts/yazi-open-in-helix.sh "$@"', block = false, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]

