# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  unstable-pinned = import (builtins.fetchTarball {
    name = "v1.0.9";
    url = https://github.com/heyyou3/nixpkgs/archive/refs/tags/v1.0.9-beta1.tar.gz;
  }) { config.allowUnfree = true; };
in {
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  nixpkgs.config.packageOverrides = pkgs: {
    displaylink = unstable-pinned.displaylink;
  };

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelModules = [ "kvm-amd" ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.extraModulePackages = with config.boot.kernelPackages; [ rtw89 ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3483c5f5-3883-4a53-b091-8acd1c731a7b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6C1D-8720";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;

  hardware.opengl.driSupport = true;
  hardware.opengl.driSupport32Bit = true;

  hardware.bluetooth.enable = true;
  hardware.bluetooth.settings = {
    General = {
      Enable = "Source,Sink,Media,Socket";
    };
  };
  hardware.pulseaudio.enable = true;
  hardware.enableAllFirmware = true;

  services = {
    xserver = {
      videoDrivers = ["amdgpu" "displaylink" "modesetting"];
    };
  };
}
