theme = "catppuccin_mocha"

[editor]
shell = ["fish", "-i", "-c"]
auto-format = false

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false
git-exclude = false
parents = false

[editor.word-completion]
enable = true
trigger-length = 3
