format = "$all$directory$character"
right_format = ""
add_newline = false

[character]
success_symbol = "[\\[I\\]](bold green)"
error_symbol = "[\\[I\\]](bold red)"
vicmd_symbol = "[\\[N\\]](bold green)"

